main_app/urls.py
from django.urls import path
from . import views
from .views import VerificationView
from django.contrib.auth import views as auth_views


app_name = "main_app"

urlpatterns = [
    path("", views.home, name="home"),
    path("home/", views.home, name="home"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    path("delete_account/<str:username>", views.delete_account, name="delete_account"),
    path("emergency_contact/", views.emergency_contact, name="emergency_contact"),
    path("create_contact/", views.create_contact, name="create_contact"),
    path("update_contact/<str:pk>/", views.update_contact, name="update_contact"),
    path("delete_contact/<str:pk>/", views.delete_contact, name="delete_contact"),
    path("emergency/", views.emergency, name="emergency"),
    path("helpline_numbers/", views.helpline_numbers, name="helpline_numbers"),
    path("women_laws/", views.women_laws, name="women_laws"),
    path('women_rights/', views.women_rights, name='women_rights'),
    path('ngo_details/', views.ngo_details, name='ngo_details'),
    path('FAQ/', views.FAQ, name='FAQ'),
    path('gallery/', views.gallery, name='gallery'),
    path('email_sent/', views.send_email, name='email_sent'),
    path("developers/", views.developers, name="developers"),
    path("contact_user/", views.contact_user, name="contact_user"),
    path("404_error/", views.page_not_found, name="404_error"),
    path("activate/<uidb64>/<token>", VerificationView.as_view(), name="activate"),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(
            template_name="main_app/password_reset.html"
        ),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="main_app/password_reset_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="main_app/password_reset_form.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="main_app/password_reset_done.html"
        ),
        name="password_reset_complete",
    ),
    path("change_password/", views.change_password, name="change_password"),
    path("check_username", views.check_username, name="check_username"),
    path("check_email", views.check_email, name="check_email"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from main_app import views
from main_app.views import VerificationView
from django.conf.urls import url, handler404
from django.views.static import serve

urlpatterns = [
    url(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    url(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", include("main_app.urls")),
    path("register/", views.register, name="register"),
    path("activate/<uidb64>/<token>", VerificationView.as_view(), name="activate"),
    path("", include("django.contrib.auth.urls")),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(
            template_name="main_app/password_reset.html"
        ),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="main_app/password_reset_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="main_app/password_reset_form.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="main_app/password_reset_done.html"
        ),
        name="password_reset_complete",
    ),
    path("accounts/", include("allauth.urls")),
    path('contact_user/', views.contact_user , name="contact_user"),
    path("404_error/", views.page_not_found, name="404_error"),
    path("delete_account/<str:username>", views.delete_account, name="delete_account"),

]
handler404 = "main_app.views.page_not_found"  # noqa

main_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class contact(models.Model):

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="contact", null=True
    )
    name = models.CharField(max_length=100)
    email = models.EmailField()
    mobile_no = models.CharField(max_length=15)
    Father = "Father"
    Mother = "Mother"
    Brother = "Brother"
    Sister = "Sister"
    Husband = "Husband"
    Friend = "Friend"
    Relative = "Relative"
    Other = "Other"
    relations = (
        (Father, "Father"),
        (Mother, "Mother"),
        (Brother, "Brother"),
        (Sister, "Sister"),
        (Husband, "Husband"),
        (Friend, "Friend"),
        (Relative, "Relative"),
        (Other, "Other"),
    )
    relation = models.CharField(max_length=10, choices=relations, default=Other)

    def __str__(self):
        return self.name


class Login(models.Model):

    Username_or_Email = models.CharField(max_length=100)
    password = models.CharField(max_length=32)

main_app/forms.py
from django.forms import ModelForm
from .models import contact, Login
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ContactForm(ModelForm):
    class Meta:
        model = contact
        fields = ["name", "email", "mobile_no", "relation"]
        Father = "Father"
        Mother = "Mother"
        Brother = "Brother"
        Sister = "Sister"
        Husband = "Husband"
        Friend = "Friend"
        Relative = "Relative"
        Other = "Other"
        relations = (
            (Father, "Father"),
            (Mother, "Mother"),
            (Brother, "Brother"),
            (Sister, "Sister"),
            (Husband, "Husband"),
            (Friend, "Friend"),
            (Relative, "Relative"),
            (Other, "Other"),
        )
        widgets = {
            "relation": forms.Select(
                choices=relations, attrs={"class": "form-control"}
            ),
        }


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        label="Email",
        error_messages={"exists": "This Email already exists!"},
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data["email"]).exists():
            raise forms.ValidationError(self.fields["email"].error_messages["exists"])
        return self.cleaned_data["email"]


class LoginForm(ModelForm):
    class Meta:
        model = Login
        fields = ["Username_or_Email", "password"]
        widgets = {
            "password": forms.PasswordInput,
        }

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import (
    PasswordChangeForm,
)
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib import messages
from .forms import ContactForm
from django.conf import settings
from .models import contact
from django.contrib.auth.models import User, auth
from .mail import send_email
from .whatsapp import send_whatsapp
from .location import lat, log
from .forms import UserCreateForm, LoginForm
from django.core.mail import EmailMessage
from django.views import View
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse
from .utils import account_activation_token
from django.http import JsonResponse,HttpResponse
import json
import urllib

# Create your views here


def home(request):
    context = {}
    return render(request, "main_app/home.html", context)


def register(request):
    if request.method == "POST":
        form = UserCreateForm(request.POST)
        username = request.POST.get("username")
        email = request.POST.get("email")
        password1 = request.POST.get("password1")  # noqa
        password2 = request.POST.get("password2")  # noqa
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            user.is_active = False
            user.save()

            uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
            domain = get_current_site(request).domain
            link = reverse(
                "activate",
                kwargs={
                    "uidb64": uidb64,
                    "token": account_activation_token.make_token(user),
                },
            )

            activate_url = "http://" + domain + link

            email_subject = "Rescue - Activate you Account!"
            email_body = (
                "Hi  "
                + user.username  # noqa
                + "  ,  Please use this link to verify your account\n"  # noqa
                + activate_url  # noqa
            )
            email = EmailMessage(
                email_subject,
                email_body,
                "noreply@gmail.com",
                [email],
            )
            messages.success(request, f"New Account Created Successfully: {username}")
            messages.success(request, "Check your email to Activate your account!")
            email.send(fail_silently=False)
            return redirect('main_app:email_sent')
        elif User.objects.filter(username=username).exists():
            messages.warning(
                request,
                "The username you entered has already been taken. Please try another username",
            )
        elif User.objects.filter(email=email).exists():
            messages.warning(
                request,
                "The Email you entered has already been taken. Please try another Email",
            )
        else:
            for msg in form.error_messages:
                messages.warning(request, f"{form.error_messages[msg]}")

    else:
        form = UserCreateForm()
    return render(request, "main_app/register.html", {"form": form})


class VerificationView(View):
    def get(self, request, uidb64, token):
        try:
            id = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=id)

            if not account_activation_token.check_token(user, token):
                return redirect(
                    "main_app:login" + "?message=" + "User already activated"
                )

            if user.is_active:
                return redirect("main_app:login")
            user.is_active = True
            user.save()

            messages.success(request, "Account activated successfully")
            return redirect("main_app:login")

        except Exception:
            pass

        return redirect("main_app:login")


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("main_app:home")


def delete_account(request, username):
    try:
        user = User.objects.get(username=username)
        user.delete()
        messages.success(
            request, user.username + ", Your account is deleted successfully!"
        )

    except User.DoesNotExist:
        messages.error(request, "User doesnot exist")

    return redirect("main_app:home")


def login_request(request):
    form = LoginForm(request.POST)
    username = request.POST.get("Username_or_Email")
    password = request.POST.get("password")
    if request.method == "POST":
        recaptcha_response = request.POST.get("g-recaptcha-response")
        url = "https://www.google.com/recaptcha/api/siteverify"
        values = {
            "secret": settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            "response": recaptcha_response,
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        if result["success"]:
            if username and password:
                if User.objects.filter(username=username).exists():
                    user = auth.authenticate(username=username, password=password)
                    if user:
                        if user.is_active:
                            login(request, user)
                            messages.success(
                                request,
                                "Welcome, " + user.username + " you are now logged in",
                            )
                            return redirect("main_app:home")

                    messages.error(
                        request, "Account is not active,please check your email"
                    )

                elif User.objects.filter(email=username).exists():
                    user = User.objects.get(email=username)
                    user = auth.authenticate(username=user.username, password=password)
                    if user:
                        if user.is_active:
                            login(request, user)
                            messages.success(
                                request,
                                "Welcome, " + user.username + " you are now logged in",
                            )
                            return redirect("main_app:home")

                    messages.error(
                        request, "Account is not active,please check your email"
                    )

                else:
                    messages.error(request, "Invalid username or password")
                    return redirect("main_app:login")
        else:
            messages.error(request, "Invalid reCAPTCHA. Please try again.")

    form = LoginForm()
    return render(request, "main_app/login.html", {"form": form})


def emergency_contact(request):
    users = User.objects.all()
    curr = 0
    for user in users:
        if request.user.is_authenticated:
            curr = user
            break
    if curr == 0:
        return redirect("main_app:login")
    contacts = contact.objects.filter(user=request.user)
    total_contacts = contacts.count()
    context = {
        "contacts": contacts,
        "total_contacts": total_contacts,
        "user": request.user,
    }
    return render(request, "main_app/emergency_contact.html", context)


def create_contact(request):
    print("method called")
    inst = contact(user=request.user)
    form = ContactForm(instance=inst)
    if request.method == "POST":
        print("post method called")
        form = ContactForm(request.POST, instance=inst)
        if form.is_valid():
            print("form is valid")
            form.save()
            messages.info(request, "New contact created successfully!!")
            messages.info(request, "An email has been sent to your contact!!")
            return redirect("main_app:emergency_contact")
        messages.error(request, "Invalid username or password")
    
    
    return render(request, "main_app/create_contact.html", {'form':form, 'recaptcha_site_key':settings.GOOGLE_RECAPTCHA_SITE_KEY})
    


def update_contact(request, pk):
    curr_contact = contact.objects.get(id=pk)
    name = curr_contact.name
    form = ContactForm(
        initial={
            "name": name,
            "email": curr_contact.email,
            "mobile_no": curr_contact.mobile_no,
            "relation": curr_contact.relation,
        }
    )
    if request.method == "POST":
        form = ContactForm(request.POST, instance=curr_contact)
        if form.is_valid():
            form.save()
            messages.error(request, f"{name} updated successfully!!")
            messages.info(request, "A message has been sent to your contact!!")
            return redirect("main_app:emergency_contact")
    context = {"form": form}
    return render(request, "main_app/create_contact.html", context)


def delete_contact(request, pk):
    curr_contact = contact.objects.get(id=pk)
    name = curr_contact.name
    if request.method == "POST":
        curr_contact.delete()
        messages.error(request, f"{name} deleted successfully!!")
        return redirect("main_app:emergency_contact")
    context = {"item": curr_contact}
    return render(request, "main_app/delete_contact.html", context)


def emergency(request):
    users = User.objects.all()
    curr = 0
    for user in users:

main_app/templates/main_app/activate_account.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}


main_app/templates/main_app/change_password.html
<!DOCTYPE html>
{% extends "main_app/common.html" %}
{% load static %}
{% load socialaccount %}

<body lang="en">
    
    {% block content %}
    <title>Rescue | Change Password</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap');
        html {
            scroll-behavior:smooth;
        }

        /* Register Page styling */
        .change-pwd-page{
            margin-top: 7em;
        }
        .change-pwd-page-img {
            width: 80%;
            display: block;
            margin: 0 auto;
            margin-bottom: 0.5em;
        }

        .change-pwd-page-title{
            font-size: 2.75rem;
            font-family: "Bebas Neue", sans-serif;
            font-weight: 900;
            text-align: center;
            letter-spacing: 0.2em;
            margin-bottom: 0.5em;
        }

        .change-pwd-page-text {
            font-size: 2rem;
            text-align: center;
        }

        .form-style {
            font-size: 1.15rem;
        }
        .form-div1{
            margin-top: 8em;
        }
        .form-div2{
            width: 80%;
            margin-top: 3em;
        }

        label {
            font-size: 1.75rem;
            color: #6C63FF;
            margin: 1em 0 0.5em 0;
            font-weight: 500;
        }

        input[type="submit"] {
            background-color: #FFF;
            color: #6C63FF;
            font-weight: bold;
            font-size: 1.5rem;
            padding: 0.5em 1.5em;
            margin: 1em 0;
            width: unset;
            cursor: pointer;
            border: 2px solid #6C63FF;
            border-radius: 5em;
            transition: all 0.3s ease-in-out;
        }

        input[type="submit"]:hover {
            color: #FFF;
            background-color: #6C63FF;
            border: 2px solid #6C63FF;
            cursor: pointer;
        }

        .change-pwd-btn{
            text-align: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            /* padding: 1.5em 0; */
        }

        .change-pwd-btn  a {
            text-decoration: none;
            color: #6C63FF;
            transition: all 0.5s ease-in-out;
            margin: 0 auto;
        }
        .change-pwd-btn a:hover {
            text-decoration: underline;
        }

        @media only screen and (max-device-width: 768px){
            .form-div1{
                margin-top: 5em;
            }
            .form-div2{
                width: 80%;
                margin-left: 3.7em;
            }
            label {
                font-size: 2.5rem;
            }
            form.form-style {
                margin: 0 auto;
                font-size: 2rem;
            }
        }

     </style> 
	    <div class="change-pwd-page" style="margin:100px;">
            <form method="POST" class="form-style"> 
                {% csrf_token %}         
                <div class="row">   
                    <div class="form-div1 col-lg-6 col-md-12 col-sm-12 col-12">
                        <h1 class="change-pwd-page-title" data-aos="fade-down">Change Password</h1>
                        <img data-aos="zoom-in" class="change-pwd-page-img" src="{% static 'Images/password.png' %}" alt="Sign Up">
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-12 col-12">
                        <div class="form-div2">{{ form }}</div>
                    </div>
                </div>  
                <div class="change-pwd-btn" align="center">
                    <input type="submit" value="Submit">
                </div>
            </form>
        
        </div>


    {% endblock %}
</body>

main_app/templates/main_app/contact_user.html
{% extends 'main_app/common.html' %}

{% block body %}
{% load static %}
<title>Rescue | Contact Us</title>
<style>  
  @import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap');

  .contact-section {
    margin-top: 100px;
  }

  .contact-info {
    height: 50%;
    width: auto;
    max-width: 500px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  }
  .info-img {
    width:100%;
    max-width: inherit;
    padding: 1em 0;
  } 
  .info-icons a {
    text-decoration: none;
    font-size: 3rem;
    text-align: center;
    color: #6C63FF;
  }
  .info-icons a:hover {
    font-size: 3rem;
    color: #ec4959;
  }
  .info-icons a i {
    height: 2px;
    border-radius: 50px;
    transform: translatey(0px);
	  animation: float 3s ease-in-out infinite;
  }
  .contact-form {
    padding: 2em;
    font-size: 1.25rem;
  }
  .contact-form-heading {
    text-align: center;
    font-size: 3rem;
    font-family: "Bebas Neue", sans-serif;
  }
  
  label {
    font-size: 1.25rem;
    color: #6C63FF;
    margin: 0.5em 0;
    font-weight: 500;
  }

  textarea {
    border-radius: 0.5em;
  }

  input[type="submit"] {
    background-color: #FFF;
    color: #6C63FF;
    font-weight: bold;
    font-size: 1.25rem;
    padding: 0.5em 1.5em;
    margin: 1em 0;
    width: unset;
    cursor: pointer;
    border: 2px solid #6C63FF;
    border-radius: 5em;
    transition: all 0.3s ease-in-out;
  }

  input[type="submit"]:hover {
    color: #FFF;
    background-color: #6C63FF;
    border: 2px solid #6C63FF;
    cursor: pointer;
  }
  @keyframes float {
    0% {
      box-shadow: 0 5px 15px 0px rgba(0,0,0,0.6);
      transform: translatey(0px);
    }
    50% {
      box-shadow: 0 25px 15px 0px rgba(0,0,0,0.2);
      transform: translatey(-20px);
    }
    100% {
      box-shadow: 0 5px 15px 0px rgba(0,0,0,0.6);
      transform: translatey(0px);
    }
  }
</style>

<link href="https://fonts.googleapis.com/css2?family=Overpass:wght@300&display=swap" rel="stylesheet">

  <!-- ***** Contact Area Start ***** -->
  {% if message_name %}
    <center>
      <h2 style="margin-top: 120px; font-family: 'Overpass';">Thanks {{ message_name }}!</h2>
      <p style="font-family: 'Overpass';">We received your email and will respond shortly...</p>
    </center>
    <br/><br/><br/>
  {% else %}

<section class="contact-section py-4 mx-auto align-items-start">
  <div class="container row mx-auto">
    <!-- Contact Information -->
    <div class="contact-info col-12 col-md-6 col-lg-6 align-self-center">
      <img src="../../static/Images/contact-page.svg" class="info-img" alt="contact illustration">
      
      <div class="info-icons">
        <a href="#" target="_blank"><i class="fab fa-github-square"></i></a>
        <a href="#" target="_blank"><i class="fab fa-linkedin"></i></a>
        <a href="#" target="_blank"><i class="fab fa-twitter-square"></i></a>
      </div>
    </div>
  
  <!-- Contact Form -->
  <div class="contact-form col-12 col-md-6 col-lg-6">
      <h2 class="contact-form-heading" data-aos="fade-left">Get in Touch</h2>
      
      <form action="/contact_user/" method="POST">
        {% csrf_token %}
        
        <label for="name">Name</label>
        <input type="text" id="name" name="name">
        
        <label for="email">Email</label>
        <input type="email" id="email" name="email">
        
        <label for="message">Message</label>
        <textarea name="message" id="message" cols="30" rows="10"></textarea>
        
        <input type="submit" class="send-message" value="Send message">
      </form>
    </div>
  </div>    
</section>
  {% endif %}
  <!-- ***** Contact Area End ***** -->
  
  {% endblock %}
  

main_app/templates/main_app/create_contact.html
<!DOCTYPE html> {% extends "main_app/common.html" %} {% load static %}
<html lang="en">
{% block content %}
<title>Rescue | Create contacts </title>
<style>
    html {
        scroll-behavior: smooth;
    }
    
    label {
        font-size: 18px;
        color: black
    }
    
    font-size: 18px;
    color: black;
}
.jumbotron {
    background-color: #f3f3f3;
    margin-left: auto;
    margin-right: auto;
    width: 60%;
}
p {
    font-size: 20px;
}
.jumbotron {
    background-color: #f3f3f3;
    margin-left: auto;
    margin-right: auto;
    width: 60%;
}
p {
    font-size: 20px;
}
.form-control {
    width: 50%;
    .form-control {
        width: 50%;
    }
    
    .container {
        position: relative;
        align-self: flex-start;
        padding-right: 20%;
        padding-left: 20%
    }
</style>

<body style="background-color:white;margin-top:150px;">


    <br>
    <div class="responsive">
        <div class="container" style=" position: relative;
    align-self: flex-start;
    padding-right: 20%;
    padding-left: 20%">
            <link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet">
            <h1 class="display-4" style="color: black; font-family: 'Bangers', cursive; margin-top: 8%; text-align: center;">
                Create a new contact!</h1>
            <link href="https://fonts.googleapis.com/css2?family=Overpass:wght@300&display=swap" rel="stylesheet">
            <p class="lead" style="font-family: 'Overpass', sans-serif; text-align: center;">Create contacts of your trustworthy people who can help you when you need their help in any emergency.</p>



            <hr class="my-4 ">
            <p style="text-align: center;">They will get notify when you are in danger!!</p>
            <br>
            <br>
            <form method="POST" style="display: contents; padding-left: 20%; ">

                {% csrf_token %}
                <div class="alert alert-info" role="alert">
                    <p align="center"><b>Note : </b>Your mobile number must include your country code such as +91, and must not contain spaces.</p>
                </div>
                {{form.as_p}}
                <br>
                <div class="text-center " style="padding-bottom: 8%; padding-top: 5%; color: rgb(50, 192, 192); ">
                    <button style="color:white; border-radius: 25px; padding-bottom:35px " class="btn btn-success btn-lg active " name="submit " type="submit "><b>Create</b></button></div>
            </form>




        </div>
    </div>
    <script src='https://www.google.com/recaptcha/api.js' style="position: absolute; margin-left: 25px;"></script>


    <div class="g-recaptcha" id="rcaptcha" data-sitekey="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"></div>
    <span id="captcha" style="color:red"></span>
    <!-- this will show captcha errors -->



</body>

{% endblock %}

</html>

main_app/templates/main_app/delete_contact.html
<!DOCTYPE html>
{% extends 'main_app/common.html' %}
{% load static %}
{% block content %}
<html lang="en">
	<title>Rescue | Delete Contacts</title>
	<style>
		.delete-page {
			width: 50%;
			position: absolute;
			top: 25%;
			left: 50%;
			transform: translate(-50%, 50%);
			text-align: center;
		}
		@media screen and (min-device-width: 425px) and (max-device-width: 768px) {

			body {
				font-size: 2rem;
			}

			.delete-page {
				width: 80%;
				position: absolute;
				top: 20%;
				left: 50%;
				transform: translate(-50%, 50%)
			}
			#footer{
				position:absolute;
				top: 150%;
			}
		}

		@media screen and (min-device-width: 375px) and (max-device-width: 425px) {

			body {
				font-size: 2rem;
			}

			.delete-page {
				width: 80%;
				position: absolute;
				top: 33%;
				left: 50%;
				transform: translate(-50%, 50%)
			}
			#footer{
				position:absolute;
				top: 150%;
			}
		}

		@media screen and (max-device-width: 375px) {

			body {
				font-size: 2rem;
			}

			.delete-page {
				width: 80%;
				position: absolute;
				top: 35%;
				left: 50%;
				transform: translate(-50%, 50%)
			}
			#footer{
				position:absolute;
				top: 150%;
			}
		}

		@media screen and (min-device-width:766px) and (max-device-width:1180px) {
			#footer{
				position:absolute;
				top: 100%;
			}
		}
		html {
			scroll-behavior:smooth;
		}

	</style>
<body style="background-color:white;margin-top:60px;">
	<br><br>
	<div class="delete-page">
		<div class="container">
			<br>
			<!-- <div class="row"> -->
			<!-- <div class="col-md-6"> -->
			<div class="card card-body" style="background-color:rgb(217,48,37); border-radius: 10px;">


				<p style="color: white;"><strong>Are you sure you want to permanently remove {{item}} contact
						?</strong></p>

				<form action="{% url 'main_app:delete_contact' item.id  %}" method="POST">

					{% csrf_token %}
					<a style="color:black; background-color:white; border-radius: 20px;" class="btn btn-warning"
						href="{% url 'main_app:emergency_contact' %}"><b>Cancel</b></b></a>

					<input style="color:black; background-color:white; border-radius: 20px; font-weight: 700;"
						class="btn btn-danger" type="submit" name="Yes">
				</form>
			</div>
		</div>
	</div>
  

	{% endblock %}

</html>